In [1]:
import numpy as np

In [7]:
x = np.array([[4., 5., 6.], [7., 8., 9.]])
y = np.array([[2., 3.], [-1, 9], [4, 6]])

In [8]:
x

array([[4., 5., 6.],
       [7., 8., 9.]])

In [9]:
y

array([[ 2.,  3.],
       [-1.,  9.],
       [ 4.,  6.]])

In [10]:
x.dot(y)

array([[ 27.,  93.],
       [ 42., 147.]])

In [11]:
# Same as
np.dot(x, y)

array([[ 27.,  93.],
       [ 42., 147.]])

In [12]:
# matrix multiplication using one dimension array

z = np.ones(3)

np.dot(x, z)

array([15., 24.])

In [13]:
from numpy.linalg import inv, qrb

In [15]:
a = np.random.randn(5, 5)
a

array([[-1.67054663, -0.75650443, -1.49285913, -0.2678747 , -0.35638957],
       [-0.54255748, -0.58111023,  0.24225701,  0.06656208, -1.40518088],
       [-0.55935605,  1.41310616,  1.28347979, -1.44377014,  0.59904382],
       [-0.28375516,  0.93366278, -0.18442276, -0.76282539, -0.25009966],
       [-0.70043493, -1.51106944,  0.51887068, -0.58468046, -0.3181766 ]])

In [17]:
# Compute the dot product on a transposed view of the same matrix
matrix = a.T.dot(a)

matrix

array([[ 3.96909992,  1.58210634,  1.33342602,  1.84495123,  1.31650708],
       [ 1.58210634,  6.06191409,  1.84603142, -1.70496088,  2.17996599],
       [ 1.33342602,  1.84603142,  4.23787575, -1.59971665,  0.84151671],
       [ 1.84495123, -1.70496088, -1.59971665,  3.0844134 , -0.48613158],
       [ 1.31650708,  2.17996599,  0.84151671, -0.48613158,  2.62418652]])

In [19]:
# Compute inverse
inv(matrix)

array([[ 2.52543067, -0.76500082, -1.35930763, -2.74956125, -0.70491943],
       [-0.76500082,  0.50927295,  0.36768492,  0.93223976,  0.01551318],
       [-1.35930763,  0.36768492,  1.04428282,  1.61154234,  0.34015787],
       [-2.74956125,  0.93223976,  1.61154234,  3.4341665 ,  0.72437034],
       [-0.70491943,  0.01551318,  0.34015787,  0.72437034,  0.74693775]])

In [22]:
q, r = qr(matrix)
q

array([[-0.79110521,  0.20694149, -0.00437202,  0.19552477, -0.54136745],
       [-0.31533914, -0.80603601,  0.32305616, -0.38257019,  0.01191389],
       [-0.26577317, -0.14552517, -0.89020134, -0.21790896,  0.26123609],
       [-0.36772834,  0.49542196,  0.30589182, -0.46506707,  0.55630546],
       [-0.26240096, -0.20214024,  0.09791509,  0.74272365,  0.57363689]])

In [23]:
r

array([[-5.01715812, -3.59885971, -2.39587355, -1.50341269, -2.46240147],
       [ 0.        , -6.11269556, -2.79138337,  3.61520874, -2.37844698],
       [ 0.        ,  0.        , -3.58896369,  1.76110287,  0.05762013],
       [ 0.        ,  0.        ,  0.        , -0.43392706,  1.41517487],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.76798486]])