In [1]:
import numpy as np

In [2]:
# demonstrating numpy efficiency

my_arr = np.arange(1000000)

my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 27 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 811 ms


In [5]:
# Applying computations to ndarrays
# Random data
data = np.random.randn(2, 3)

In [6]:
print(data)

print(data * 10)

data + data

[[-0.08578087  0.64484767  2.43683666]
 [-0.37729762  0.1298203   0.13077904]]
[[-0.85780875  6.44847665 24.36836664]
 [-3.7729762   1.29820302  1.30779044]]


array([[-0.17156175,  1.28969533,  4.87367333],
       [-0.75459524,  0.2596406 ,  0.26155809]])

In [11]:
data.shape

(2, 3)

In [18]:
d1 = [6, 7, 8, 9, 0, 2.2]

arr1 = np.array(d1)

arr1

array([6. , 7. , 8. , 9. , 0. , 2.2])

In [30]:
d2 = [[4, 3, 2, 1], [9, 8, 7, 6]]

arr2 = np.array(d2)

# arr2.shape
# arr2.ndim

arr1.dtype

arr2.dtype

dtype('int32')

In [47]:
# Other numpy functions for ndarray creation

np.zeros((2, 3))

np.ones((3, 4))

np.empty((2, 3, 2))

type(np.arange(5))

numpy.ndarray