In [1]:
import numpy as np

In [2]:
# demonstrating numpy efficiency

my_arr = np.arange(1000000)

my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 27 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 837 ms


In [5]:
# Applying computations to ndarrays
# Random data
data = np.random.randn(2, 3)

In [6]:
print(data)

print(data * 10)

data + data

[[-0.00385648  0.29894388  0.42881137]
 [ 0.73444922  0.41595608  0.97788031]]
[[-0.03856483  2.98943885  4.28811368]
 [ 7.34449223  4.1595608   9.7788031 ]]


array([[-0.00771297,  0.59788777,  0.85762274],
       [ 1.46889845,  0.83191216,  1.95576062]])

In [7]:
data.shape

(2, 3)

In [8]:
d1 = [6, 7, 8, 9, 0, 2.2]

arr1 = np.array(d1)

arr1

array([6. , 7. , 8. , 9. , 0. , 2.2])

In [9]:
d2 = [[4, 3, 2, 1], [9, 8, 7, 6]]

arr2 = np.array(d2)

# arr2.shape
# arr2.ndim

arr1.dtype

arr2.dtype

dtype('int32')

In [10]:
# Other numpy functions for ndarray creation

np.zeros((2, 3))

np.ones((3, 4))

np.empty((2, 3, 2))

type(np.arange(5))

numpy.ndarray

In [15]:
# Messing around with type

int_array = np.arange(10)

int_array

decimals = np.array([.11, .22], dtype=np.float64)

# Casting the dtype of another array
int_array.astype(decimals.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Indexing/slicing
arr5 = np.arange(10)

arr5[0:3]

# 'Broadcasting' onto arrays
arr5[0:3] = 50

arr5

In [30]:
# array slices as views of original array

arr_slice = arr5[0:3]
arr_slice

# Because arr_slice is just a 'view' of arr5[0:3]
# When I make a change to arr_slice[1] it technically modifies
# arr5[1]
arr_slice[1] = 123

# Crazy!
arr5

# If you did want to copy, just .copy()

arr_slice2 = arr5[0:3].copy()

arr_slice2[:] = 999

arr_slice2

# Voila!
arr5

array([ 50, 123,  50,   3,   4,   5,   6,   7,   8,   9])

In [34]:
# On to two dimension arrays!

arr_md = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr_md

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr_md[0][2]
# same as
arr_md[0, 2]

# But both bad because of index chaining?
# Nvm I guess loc iloc aren't properties of NumPy arrays

for row in range(len(arr_md)):
    for column in range(len(arr_md)):
        print(arr_md[row, column])

1
2
3
4
5
6
7
8
9


In [48]:
# N Dimensional arrays

arr_3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

arr_3d[0, 1, 1]

arr_3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [54]:
arr_md

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
# Same stuff but with slicing instead indexing
arr_md
arr_md[0:2]

# YOU CAN MIX INDEXES AND SLICES! Cool
arr_md[:3, 0]

arr_md[:2, 1:2]

arr_md[:, :2]

arr_md[1:3, 1:3]

# and if you want to destroy things

arr_md[1:3, 1:3] * 3

arr_md[1:3, 1:3] = 11

arr_md

array([[ 1,  2,  3],
       [ 4, 11, 11],
       [ 7, 11, 11]])