In [1]:
import numpy as np

In [3]:
# demonstrating numpy efficiency

my_arr = np.arange(1000000)

my_list = list(range(1000000))

In [6]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 22.9 ms


In [7]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 809 ms


In [8]:
# Applying computations to ndarrays
# Random data
data = np.random.randn(2, 3)

In [18]:
print(data)

print(data * 10)

data + data

[[-0.89726854 -0.55929821 -0.57298846]
 [ 1.26732372  1.75212959  0.38686915]]
[[-8.9726854  -5.5929821  -5.72988457]
 [12.67323719 17.52129587  3.86869147]]


array([[-1.79453708, -1.11859642, -1.14597691],
       [ 2.53464744,  3.50425917,  0.77373829]])