In [5]:
import numpy as np

In [6]:
# simple functions to apply to arrays
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
# Referred to as unary functions because they only require a single element input
np.sqrt(arr)
np.exp(arr)

np.modf(arr)
np.isfinite(arr)
np.isnan(arr)

array([False, False, False, False, False, False, False, False])

In [12]:
# Others are referred to as binary because they require two array element inputs
x = np.random.randn(8)
y = np.random.randn(8)

In [16]:
np.maximum(x, y)

array([0.33186693, 1.76163374, 2.12793138, 0.47363661, 1.36869937,
       1.45803345, 1.78607163, 1.29183647])

In [32]:
arr1 = np.random.randn(7) * 4
# Some unary functions can optionally return multiple arrays

remainder, whole = np.modf(arr1)

In [35]:
# arr1
# remainder
whole

array([ 2., -3., 11., -3., -6.,  4.,  0.])